/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlybanhang.form;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import quanlybanhang.enity.Ban;
import quanlybanhang.service.SVBan;

/**
 *
 * @author admin
 */
public class FormQuanLyBan extends javax.swing.JFrame {

    /**
     * Creates new form FormQuanLyBan
     */
    private SVBan svban;
    private int trangthai;

    public FormQuanLyBan() {
        svban = new SVBan();
        trangthai = 0;
        initComponents();
        duaDuLieuVaoTable();
        dis_or_en_ableButton();
    }
     private void dis_or_en_ableButton() {
        if (trangthai == 1) {
            this.idTXT.setEditable(false);
            this.sobanTXT.setEditable(true);
            this.suaBTN.setEnabled(false);
            this.xoaBTN.setEnabled(false);
            this.themBTN.setEnabled(true);
            this.luuBTN.setEnabled(true);
        } else if (trangthai == 2) {
            this.suaBTN.setEnabled(true);
            this.themBTN.setEnabled(false);
            this.xoaBTN.setEnabled(false);
            this.idTXT.setEditable(false);
            this.sobanTXT.setEditable(true);
            this.luuBTN.setEnabled(true);
        } else {
            this.suaBTN.setEnabled(true);
            this.themBTN.setEnabled(true);
            this.xoaBTN.setEnabled(true);
            this.idTXT.setEditable(false);
            this.sobanTXT.setEditable(false);
            this.luuBTN.setEnabled(false);
        }
    }


    public void duaDuLieuVaoTable() {
        String a = "Bàn Số ";
        String column[] = {"ID", "SỐ BÀN"};
        String data[][] = new String[1000][1000];
        List<Ban> Danh_sach_ban = new ArrayList<>();
        Danh_sach_ban = svban.danhSachBan();
        int i = 0, j = 0;
        for (Ban value : Danh_sach_ban) {
            data[i][j] = Integer.toString(value.getId_ban());
            data[i][j + 1] = a.concat(Integer.toString(value.getSoBan()));
            i++;
        }
        TableModel model = new DefaultTableModel(data, column);
        this.jTable1.setModel(model);
    }

    public String laySoBan(String tenban) {
        int index = tenban.lastIndexOf(" ");
        index++;
        String a = "";
        for (int i = index; i < tenban.length(); i++) {
            a = a.concat(Character.toString(tenban.charAt(i)));
        }
        return a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        suaBTN = new javax.swing.JButton();
        luuBTN = new javax.swing.JButton();
        themBTN = new javax.swing.JButton();
        xoaBTN = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        sobanTXT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idTXT = new javax.swing.JTextField();
        luuBTN1 = new javax.swing.JButton();

        jButton4.setText("XÓA");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "STT", "TÊN BÀN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("DANH SÁCH BÀN");

        suaBTN.setText("SỬA");
        suaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaBTNActionPerformed(evt);
            }
        });

        luuBTN.setText("LƯU");
        luuBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuBTNActionPerformed(evt);
            }
        });

        themBTN.setText("THÊM");
        themBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themBTNActionPerformed(evt);
            }
        });

        xoaBTN.setText("XÓA");
        xoaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaBTNActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        sobanTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobanTXTActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("SỐ BÀN");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("ID_BÀN");

        idTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTXTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(idTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sobanTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sobanTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        luuBTN1.setText("RELOAD");
        luuBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuBTN1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(themBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(suaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(xoaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(luuBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(luuBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(luuBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(themBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xoaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(luuBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void luuBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuBTNActionPerformed
        // TODO add your handling code here:
        if (trangthai == 1) {
            String soban = this.sobanTXT.getText();

            Ban bn = new Ban();
            // soban=laySoBan(soban);
            try {
                int Soban = Integer.parseInt(soban);
                bn.setBan(Soban);
                if (svban.themBan(bn) != 0) {
                    JPanel Frame = new JPanel();
                    JOptionPane.showMessageDialog(Frame, "Thêm Bàn Thành Công");
                    duaDuLieuVaoTable();
                    this.trangthai = 0;
                    dis_or_en_ableButton();

                } else {
                    JPanel Frame = new JPanel();
                    JOptionPane.showMessageDialog(Frame, "Không Thể Thêm Được Số Bàn Đã Tồn Tại");
                }
            } catch (NumberFormatException e) {
                e.printStackTrace();
                JPanel Frame = new JPanel();
                JOptionPane.showMessageDialog(Frame, "Vui Lòng Nhập Vào Một Số");
            }

        }
        if (this.trangthai == 2) {

            String soban = this.sobanTXT.getText();
            int idban = Integer.parseInt(this.idTXT.getText());
            //   int soban =Integer.parseInt(soban1);
            Ban bn = new Ban();
            // soban=laySoBan(soban);
            try {
                int Soban = Integer.parseInt(soban);
                bn.setBan(Soban);
                bn.setId_ban(idban);
                if (svban.suaBan(bn) != 0) {
                    JPanel Frame = new JPanel();
                    JOptionPane.showMessageDialog(Frame, "Sửa Bàn Thành Công");
                    duaDuLieuVaoTable();
                    this.trangthai = 0;
                    dis_or_en_ableButton();

                } else {
                    JPanel Frame = new JPanel();
                    JOptionPane.showMessageDialog(Frame, "Không Thể Sửa Được Số Bàn Đã Tồn Tại");
                }
            } catch (NumberFormatException e) {
                e.printStackTrace();
                JPanel Frame = new JPanel();
                JOptionPane.showMessageDialog(Frame, "Vui Lòng Nhập Vào Một Số");
            }

        }

    }//GEN-LAST:event_luuBTNActionPerformed

    private void themBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themBTNActionPerformed
        // TODO add your handling code here:
        this.trangthai = 1;
        dis_or_en_ableButton();
    }//GEN-LAST:event_themBTNActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void xoaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaBTNActionPerformed
        // TODO add your handling code here:
        Ban ban = new Ban();
        int index = this.jTable1.getSelectedRow();
        String value_cell_id = this.jTable1.getValueAt(index, 0).toString();
        String value_cell_soban = this.laySoBan(this.jTable1.getValueAt(index, 1).toString());
        this.idTXT.setText(value_cell_id);
        this.sobanTXT.setText(value_cell_soban);

        ban.setId_ban(Integer.parseInt(value_cell_id));
        JPanel frame = new JPanel();
        int kq = JOptionPane.showConfirmDialog(frame,
                "Bạn có chắc muốn xóa thức uống này",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (kq == JOptionPane.YES_OPTION) {
            SVBan svb = new SVBan();

            if (svb.xoaBan(ban) == 0) {
                JOptionPane.showMessageDialog(frame, "Xóa không thành công");
            }
        }
        duaDuLieuVaoTable();

    }//GEN-LAST:event_xoaBTNActionPerformed

    private void sobanTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobanTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sobanTXTActionPerformed

    private void suaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaBTNActionPerformed
        // TODO add your handling code here:
        this.trangthai = 2;
        int index = this.jTable1.getSelectedRow();
        String value_cell_id = this.jTable1.getValueAt(index, 0).toString();
        String value_cell_soban = this.laySoBan(this.jTable1.getValueAt(index, 1).toString());
        this.idTXT.setText(value_cell_id);
        this.sobanTXT.setText(value_cell_soban);
        dis_or_en_ableButton();
    }//GEN-LAST:event_suaBTNActionPerformed

    private void idTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTXTActionPerformed

    private void luuBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuBTN1ActionPerformed
        // TODO add your handling code here:
        this.trangthai=0;
        this.suaBTN.setEnabled(true);
            this.themBTN.setEnabled(true);
            this.xoaBTN.setEnabled(true);
            this.idTXT.setEditable(false);
            this.sobanTXT.setEditable(false);
            this.luuBTN.setEnabled(false);
    }//GEN-LAST:event_luuBTN1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQuanLyBan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idTXT;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton luuBTN;
    private javax.swing.JButton luuBTN1;
    private javax.swing.JTextField sobanTXT;
    private javax.swing.JButton suaBTN;
    private javax.swing.JButton themBTN;
    private javax.swing.JButton xoaBTN;
    // End of variables declaration//GEN-END:variables
}
