/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlybanhang.form;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import quanlybanhang.enity.Ban;
import quanlybanhang.enity.ChiTietHoaDon;
import quanlybanhang.enity.HoaDon;
import quanlybanhang.enity.ThucUong;
import quanlybanhang.publicfunction.KhoaChinh;
import quanlybanhang.service.SVBan;
import quanlybanhang.service.SVHoaDon;
import quanlybanhang.service.SVThucUong;

/**
 *
 * @author admin
 */
public class FromQuanLiBan extends javax.swing.JFrame {

    /**
     * Creates new form FromQuanLiBan
     */
    private List<ThucUong> danhsachthucuong;
    private String bangchitiethoadon[][];
    private long tongtien;
    private String bangban[][];
  //  private String bangchitiethoadon[][];

    public FromQuanLiBan() {

        initComponents();
        // initComponents();
        danhsachthucuong = new ArrayList<>();
        bangchitiethoadon = new String[1000][10];
        bangban = new String[1000][10];
       // bangchitiethoadon = new String[1000][10];
        duaDuLieuVaoTable();
        // duaDuLieuVaoCombobox();
    }

    int demSoPhanTuTrongMang(String a[][]) {
        int dem = 0;
        for (int i = 0; i < a.length; i++) {
            if (a[i][0] != null) {
                dem = dem + 1;
            } else {
                break;
            }
        }
        return dem;
    }
//    public void duaDuLieuVaoCombobox(){
//       danhsachthucuong =new ArrayList<>();
//       SVThucUong svtu =new SVThucUong();
//       danhsachthucuong =svtu.danhSachThucUong();
//       for(ThucUong values:danhsachthucuong){
//           this.jComboBox1.addItem(values.getTenthucuong());
//       }
//    }

    void themDuLieuVaoTable(String a[][], String b, String c, String d, String e) {
        a[demSoPhanTuTrongMang(a)][0] = b;
        a[demSoPhanTuTrongMang(a) - 1][1] = c;
        a[demSoPhanTuTrongMang(a) - 1][2] = d;
        a[demSoPhanTuTrongMang(a) - 1][3] = e;
    }

    public void duaDuLieuVaoTable() {
        String[] column = {"SỐ BÀN", "TRẠNG THÁI"};
        List<Ban> danh_sach_ban = new ArrayList<>();
        SVBan ban = new SVBan();
        danh_sach_ban = ban.danhsachban_hoadon();
        int i = 0;
        String trangthai;
        for (Ban value : danh_sach_ban) {
            this.bangban[i][0] = Integer.toString(value.getSoBan());
            if (value.getHoadon().getTrangthai() == 1) {
                trangthai = "Đang sử dụng";
            } else {
                trangthai = "Trống";
            }
            this.bangban[i][1] = trangthai;
            this.bangban[i][2] = Integer.toString(value.getId_ban());
            this.bangban[i][3] = value.getHoadon().getMahoadon();
            i = i + 1;
        }
        TableModel model = new DefaultTableModel(bangban,column);
        this.banTable.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        banTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        chitiethoadonTB = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        giatienTXT = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        xacnhanBTN = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("HÓA ĐƠN");

        banTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        banTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        banTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "SỐ BÀN", "TRẠNG THÁI"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(banTable);

        chitiethoadonTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "ĐÒ ĂN/ THỨC UỐNG", "SỐ LUỌNG", "GIÁ TIỀN", "THÀNH TIỀN"
            }
        ));
        jScrollPane2.setViewportView(chitiethoadonTB);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("TỔNG TIỀN PHẢI TRẢ:");

        giatienTXT.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        giatienTXT.setText("200000");
        giatienTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giatienTXTActionPerformed(evt);
            }
        });

        jButton4.setText("THÊM");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("DANH SÁCH BÀN");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlybanhang/form/house-icon.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("TRANG CHỦ");

        xacnhanBTN.setText("XÁC NHẬN THANH TOÁN");
        xacnhanBTN.setEnabled(false);
        xacnhanBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xacnhanBTNActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlybanhang/form/export-icon (1).png"))); // NOI18N
        jButton8.setText("XUẤT HÓA ĐƠN");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton1.setText("XEM CHI TIẾT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(296, 296, 296))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(giatienTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(xacnhanBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton8)))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(313, 313, 313)
                    .addComponent(jLabel3)
                    .addContainerGap(1056, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(giatienTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addComponent(xacnhanBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(108, 108, 108)
                    .addComponent(jLabel3)
                    .addContainerGap(1049, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void giatienTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giatienTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giatienTXTActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          int index = this.banTable.getSelectedRow();
          String trangthai = this.bangban[index][1];
          
          int idban=Integer.parseInt(this.bangban[index][2]);
          
          String mahoadon;
          if( trangthai.compareToIgnoreCase("Đang Sử Dụng")==0 ){
              mahoadon=this.bangban[index][3];
          }
          else {
            KhoaChinh kc = new KhoaChinh("D:\\JAVASWING\\QuanLyBanHang\\JavaApplication10\\src\\index_1.txt");
            mahoadon = kc.taoKhoaChinh("HD");
          }
       // KhoaChinh kc = new KhoaChinh("D:\\JAVASWING\\QuanLyBanHang\\JavaApplication10\\src\\index_1.txt");
        //String mahoadon = kc.taoKhoaChinh("HD");
        new FormHoaDon(idban,trangthai,mahoadon,this.bangchitiethoadon).setVisible(true);
        // this.banTable.
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      
        this.bangchitiethoadon =new String[1000][10];
        int index = this.banTable.getSelectedRow();
        List<ChiTietHoaDon> cthd = new ArrayList<>();
        SVHoaDon svh = new SVHoaDon();
        cthd = svh.layChiTietHoaDonTheoBan(Integer.parseInt(this.bangban[index][2]));
        

        int stt = 1;
        int i = 0;
        for (ChiTietHoaDon values : cthd) {
            this.bangchitiethoadon[i][0] = Integer.toString(stt);
            this.bangchitiethoadon[i][1] = values.getThucuong().getTenthucuong();
            this.bangchitiethoadon[i][2] = Long.toString(values.getThucuong().getGia().getGiathucuong());
            this.bangchitiethoadon[i][3] = Integer.toString(values.getSl());
            this.bangchitiethoadon[i][4] = Long.toString(values.getThucuong().getGia().getGiathucuong() * values.getSl());
            this.bangchitiethoadon[i][5] = values.getThucuong().getMathucuong();
            i++;
            stt++;
        }
        String[] column ={"STT","Tên Thức Uống","Giá Tiền","Số Lượng","Thành Tiền"};
        
        TableModel model = new DefaultTableModel(this.bangchitiethoadon, column);
        this.chitiethoadonTB.setModel(model);
        if(this.demSoPhanTuTrongMang(this.bangchitiethoadon)==0){
            this.xacnhanBTN.setEnabled(false);
        }
        else {
             this.xacnhanBTN.setEnabled(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void xacnhanBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xacnhanBTNActionPerformed
        // TODO add your handling code here:
        int index = this.banTable.getSelectedRow();
        int idban=Integer.parseInt(this.bangban[index][2]);
        String mahoadon = this.bangban[index][3];
        HoaDon hd =new HoaDon();
        hd.setMahoadon(mahoadon);
        SVHoaDon svhd =new SVHoaDon();
        if(svhd.capNhatHoaDon(hd) !=0){
            JPanel Frame = new JPanel();
            JOptionPane.showMessageDialog(Frame, "Thanh Toán Thành Công");
            this.setVisible(false);
            new FromQuanLiBan().setVisible(true);
        }
        else {
            JPanel Frame = new JPanel();
            JOptionPane.showMessageDialog(Frame, "Thanh Toán Thất Bại");
        }
        
    }//GEN-LAST:event_xacnhanBTNActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         new FromMenu().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromQuanLiBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromQuanLiBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromQuanLiBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromQuanLiBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromQuanLiBan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable banTable;
    private javax.swing.JTable chitiethoadonTB;
    private javax.swing.JTextField giatienTXT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton xacnhanBTN;
    // End of variables declaration//GEN-END:variables
}
