/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlybanhang.form;

import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import quanlybanhang.enity.GiaTien;
import quanlybanhang.enity.ThucUong;
import quanlybanhang.publicfunction.KhoaChinh;
import quanlybanhang.service.SVThucUong;

/**
 *
 * @author admin
 */
public class FromThucUong extends javax.swing.JFrame {

    /**
     * Creates new form FromThucUong
     */
    private int trangthai;
    private SVThucUong svnThucUong;
    private String masanpham;

    public void duaDuLieuVaoTable() {
        this.jTextField1.setEditable(false);
        List<ThucUong> danhsachthucuong = new ArrayList<>();
        SVThucUong svt = new SVThucUong();
        danhsachthucuong = svt.danhSachThucUong();
        String[] column = {"Mã Thức Uống", "Tên Thức Uống", "Giá"};
        String[][] data = new String[1000][1000];
        int i = 0, j = 0;
        for (ThucUong values : danhsachthucuong) {
            data[i][j] = values.getMathucuong();
            data[i][j + 1] = values.getTenthucuong();
            data[i][j + 2] = Long.toString(values.getGia().getGiathucuong());
            i++;
        }

//        String[][] data = {
//            {"ABCDEFGHIJKLMNOPQRSTUVWXYZ","Con Chó"},
//        };
        TableModel model = new DefaultTableModel(data, column);
        this.jTable1.setModel(model);
    }

    private void dis_or_en_ableButton() {
        if (trangthai == 1) {
            this.jTextField1.setEditable(true);
            this.giaTXT.setEditable(true);
            this.suaBTN.setEnabled(false);
            this.xoaBTN.setEnabled(false);
            this.themBTN.setEnabled(true);
            this.luuBTN.setEnabled(true);
        } else if (trangthai == 2) {
            this.suaBTN.setEnabled(true);
            this.themBTN.setEnabled(false);
            this.xoaBTN.setEnabled(false);
            this.jTextField1.setEditable(true);
            this.giaTXT.setEditable(true);
            this.luuBTN.setEnabled(true);
        } else {
            this.suaBTN.setEnabled(true);
            this.themBTN.setEnabled(true);
            this.xoaBTN.setEnabled(true);
            this.jTextField1.setEditable(true);
            this.giaTXT.setEditable(true);
            this.luuBTN.setEnabled(false);
        }
    }

    public FromThucUong() {
        initComponents();
        trangthai = 0;
        svnThucUong = new SVThucUong();
        masanpham = "";
        duaDuLieuVaoTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        suaBTN = new javax.swing.JButton();
        xoaBTN = new javax.swing.JButton();
        luuBTN = new javax.swing.JButton();
        themBTN = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        giaTXT = new javax.swing.JTextField();
        luuBTN1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("DANH SÁCH ĐỒ ĂN THỨC UỐNG");

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Thức Uống", "Tên Thức Uống", "Giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        suaBTN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        suaBTN.setText("SỬA");
        suaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaBTNActionPerformed(evt);
            }
        });

        xoaBTN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        xoaBTN.setText("XÓA");
        xoaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaBTNActionPerformed(evt);
            }
        });

        luuBTN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        luuBTN.setText("LƯU");
        luuBTN.setEnabled(false);
        luuBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuBTNActionPerformed(evt);
            }
        });

        themBTN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        themBTN.setText("THÊM");
        themBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themBTNActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlybanhang/form/house-icon.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel3.setText("TRANG CHỦ");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("TÊN THỨC UỐNG");

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("GIÁ TIỀN");

        giaTXT.setEditable(false);
        giaTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giaTXTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(giaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(241, 241, 241))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(giaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        luuBTN1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        luuBTN1.setText("RELOAD");
        luuBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuBTN1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(themBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(suaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(xoaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(luuBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(luuBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addGap(127, 127, 127))
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xoaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(luuBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(luuBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(149, 149, 149))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void suaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaBTNActionPerformed
        // TODO add your handling code here:

        int index_row = this.jTable1.getSelectedRow();
        if (index_row != -1) {
            String value_cell_masanpham = (String) this.jTable1.getValueAt(index_row, 0);
            String value_cell_tensanpham = (String) this.jTable1.getValueAt(index_row, 1);
            String value_cell_giatien = (String) this.jTable1.getValueAt(index_row, 2);

            this.jTextField1.setText(value_cell_tensanpham);
            this.giaTXT.setText(value_cell_giatien);
            this.masanpham = value_cell_masanpham;

            this.trangthai = 2;
            dis_or_en_ableButton();
        } else {
            JPanel Frame = new JPanel();
            JOptionPane.showMessageDialog(Frame, "Vui Lòng Chọn Thức Uống");
        }


    }//GEN-LAST:event_suaBTNActionPerformed

    private void luuBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuBTNActionPerformed
        // TODO add your handling code here:
        String tenthucuong = this.jTextField1.getText().toString();
        String giatien = this.giaTXT.getText();
        long giatien1 = Long.parseLong(giatien);
        if (this.trangthai == 1) {
            GiaTien gia = new GiaTien();
            gia.setGiathucuong(giatien1);
            KhoaChinh key = new KhoaChinh("D:\\JAVASWING\\QuanLyBanHang\\JavaApplication10\\src\\index.txt");
            String khoachinh = key.taoKhoaChinh("TU");
            ThucUong tu = new ThucUong(khoachinh, tenthucuong, gia);
            if (svnThucUong.themThucUong(tu) != 0) {
                JPanel Frame = new JPanel();
                JOptionPane.showMessageDialog(Frame, "Thêm Thức Uống Thành Công");
                duaDuLieuVaoTable();
                this.jTextField1.setText("");
                this.jTextField1.setEditable(false);

                this.giaTXT.setText("");
                this.giaTXT.setEditable(false);

                this.suaBTN.setEnabled(true);
                this.xoaBTN.setEnabled(true);
                this.trangthai = 0;
                dis_or_en_ableButton();
            } else {
                JPanel Frame = new JPanel();
                JOptionPane.showMessageDialog(Frame, "Không Thể Thêm Được");
            }
        }
        if (this.trangthai == 2) {

            String mathucuong = this.masanpham.toString();
            String gia = this.giaTXT.getText();
            GiaTien gia1 = new GiaTien();
            gia1.setGiathucuong(giatien1);
            // String tenthucuong =this.jTextField1.getText();
            ThucUong TU = new ThucUong();
            TU.setMathucuong(mathucuong);
            TU.setTenthucuong(tenthucuong);
            TU.setGia(gia1);

            if (svnThucUong.capNhatThucUong(TU) != 0) {
                JPanel Frame = new JPanel();
                JOptionPane.showMessageDialog(Frame, "Cập Nhật Thức Uống Thành Công");
                duaDuLieuVaoTable();
                this.jTextField1.setText("");
                this.jTextField1.setEditable(false);

                this.giaTXT.setText("");
                this.giaTXT.setEditable(false);

                this.suaBTN.setEnabled(true);
                this.xoaBTN.setEnabled(true);
                this.themBTN.setEnabled(true);
                this.themBTN.setEnabled(true);
                this.trangthai = 0;
                dis_or_en_ableButton();
            } else {
                JPanel Frame = new JPanel();
                JOptionPane.showMessageDialog(Frame, "Không Thể Cập Nhật");
            }
        }


    }//GEN-LAST:event_luuBTNActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void themBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themBTNActionPerformed
        // TODO add your handling code here:

        this.trangthai = 1;
        dis_or_en_ableButton();
    }//GEN-LAST:event_themBTNActionPerformed

    private void giaTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giaTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giaTXTActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void luuBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuBTN1ActionPerformed
        // TODO add your handling code here:
        this.giaTXT.setText("");
        this.jTextField1.setText("");
        this.themBTN.setEnabled(true);
        this.suaBTN.setEnabled(true);
        this.xoaBTN.setEnabled(true);

    }//GEN-LAST:event_luuBTN1ActionPerformed

    private void xoaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaBTNActionPerformed
        // TODO add your handling code here:
        int index_row = this.jTable1.getSelectedRow();
        String value_cell_masanpham = (String) this.jTable1.getValueAt(index_row, 0);
        JPanel frame = new JPanel();
        int kq = JOptionPane.showConfirmDialog(frame,
                "Bạn có chắc muốn xóa thức uống này",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (kq == JOptionPane.YES_OPTION) {
            SVThucUong svt = new SVThucUong();
            svt.xoaThucUong(value_cell_masanpham);
            duaDuLieuVaoTable();
            dis_or_en_ableButton();
        }
    }//GEN-LAST:event_xoaBTNActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        new FromMenu().setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromThucUong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromThucUong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromThucUong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromThucUong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromThucUong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField giaTXT;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton luuBTN;
    private javax.swing.JButton luuBTN1;
    private javax.swing.JButton suaBTN;
    private javax.swing.JButton themBTN;
    private javax.swing.JButton xoaBTN;
    // End of variables declaration//GEN-END:variables
}
